# Generated by Django 5.0.6 on 2024-05-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="profile_image/"),
        ),
    ]
