# Generated by Django 5.0.6 on 2024-05-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_products", "0001_initial"),
        ("app_profiles", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("products", models.ManyToManyField(to="app_products.product")),
                (
                    "team_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_profiles.profile",
                    ),
                ),
            ],
        ),
    ]
