# Generated by Django 5.0.6 on 2024-05-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_emails", "0002_alter_subscriptioncategory_options_email_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="email_attachments/"
            ),
        ),
    ]
