# Generated by Django 5.0.6 on 2024-05-24 05:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_emails", "0003_alter_email_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
